### ISSUE TITLE
Automated incentive payments

### ISSUE THREAD

**Issue by rugilmartin** [gsbDBI/facebook_adaptive#2]
Research [africastalking.com](africastalking.com) as a new way to automate sending credit.
- How much would we pay to use africastalking (is there monthly subscription or just % taken out of every airtime sent)?
- Can we send an SMS with the airtime - is that an extra cost/how much?
- Are there any limitations to the system (e.g., limits of amount/number of airtime/sms can send in single day?)
- Do their API and tools look straightforward and easy to use for sending a few thousand ppl airtime in a given day? (Plan to tell ppl at end of survey that they’ll receive their airtime within 3 days to give time to verify they didnt take survey more than once, and make sure they actually took survey)
- How do you pay for service? Telerivet (used in previous experiment) requires buying credits up front to them deduct from (which is annoying because you always end up w/extra)?

Find out how much Zapier costs for ~5,000 users per month

**Comment by rugilmartin** [comment]
## Africa's Talking
- How much would we pay to use africastalking? For airtime, we would pay **2-6% of the amount sent.** The exact rate depends on the country, carrier, and amount sent. For bulk SMS, we would pay about $0.01/message. There doesn’t seem to be any subscription fee.
- Can we send an SMS with the airtime? **No.** If we want to send an SMS, we have to do it separately.
- Are there any limitations to the system? **Yes.** There is an upper limit of 1,000 recipients per request and there are lower and upper limits on the amount of airtime you can send in a single request. However, you can do multiple requests. The limits are listed in full [here.](https://build.at-labs.io/docs/airtime%2Fsending)
- Do their API and tools look straightforward and easy to use for sending airtime to a few thousand people in a day? **Yes.** They support Java, Python, and other languages and their website has pretty complete code samples. To send a few thousand people airtime, we would need a few requests but this seems easy in Python.
- How do you pay for service? **Still TBD.** I haven’t been able to find this information on their website yet. It is confusing because the “payments” tab on their developer page actually refers to tools for developing mobile payments apps. It doesn’t tell you how to pay for their airtime or SMS tools. If I cannot find this information, I will send them an email to ask.

## Zapier
- For 5000 users/month, we need at least 15000 tasks.
- Each user requires 3 tasks: Get data from Chatfuel, get stored probabilities and compute random arm assignment, send data back to Chatfuel
- For a premium subscription with 15,000 tasks: $189/month billed annually or **$236.25 month-to-month.**
- We could also get a "team" subscription, but that is even more expensive and I don't think we need to be able to collaborate within Zapier.

**Comment by rugilmartin** [comment]
An additional note: It looks like there are two forms we need to fill out before Africa's Talking will activate our account and allow us to send airtime. I have these forms and they are not extensive, so I think we just need to remember to submit them by email before starting to send email.

**Comment by LeahRosenzweig** [comment]
### Africa's Talking

Thanks @rugilmartin - just adding a couple of notes/questions to return to when we get closer to launching.

1. Is there a way to automate payments for respondents who completed the survey AND spent something like >5 minutes in duration to finish (e.g. not just ppl clicking through without answering)?
2. I think we will want to send an SMS with airtime (e.g. "Thank you for taking our Covid-19 survey. We have sent you airtime.") so that they know to look out for the airtime and know it came from us.

**Comment by mollyow** [comment]
Ongoing discussion moved to #7.
